In [20]:
# Creamos un dataframe que tenga todos los ID de paraderos de Santiago usando
# https://raw.githubusercontent.com/JoseDTPM/geojson-Transantiago/refs/heads/main/Paraderos-Santiago-Chile.geojsonl.json

from os import listdir
listdir("data")
import pandas as pd

file = "data/Paraderos-Santiago-Chile.geojsonl.json"
df = pd.read_json(file, lines=True)
properties_df = pd.json_normalize(df["properties"])
geometry_df = pd.json_normalize(df["geometry"])
coordinates_df = geometry_df[["coordinates"]]
print(coordinates_df)
# Seleccionamos la columna que corresponde al ID de los paraderos.
stops_df = properties_df[["SIMT"]]
stops_df["coordinates"] = coordinates_df
stops_df_clean = pd.DataFrame()
stops_df_clean["SIMT"] = stops_df["SIMT"].unique()

                    coordinates
0      [-70.823088, -33.572525]
1        [-70.8189, -33.571649]
2       [-70.818197, -33.57202]
3       [-70.817967, -33.57187]
4      [-70.816035, -33.574243]
...                         ...
11793  [-70.506901, -33.332828]
11794  [-70.499667, -33.356539]
11795   [-70.499282, -33.34372]
11796  [-70.495669, -33.342486]
11797  [-70.496589, -33.340103]

[11798 rows x 1 columns]

/var/folders/n7/pzg1jxmx3rnghhw_xqxj4fc00000gn/T/ipykernel_52899/3629709076.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stops_df["coordinates"] = coordinates_df

In [23]:
exploded_df = stops_df.copy()
exploded_df[['Latitud','Longitud']] = pd.DataFrame(exploded_df["coordinates"].tolist(), index=exploded_df.index)
exploded_df = exploded_df[['SIMT', 'Latitud', 'Longitud']]
exploded_df

         SIMT    Latitud   Longitud
0      PI1923 -70.823088 -33.572525
1      PI1935 -70.818900 -33.571649
2      PI1926 -70.818197 -33.572020
3      PI1925 -70.817967 -33.571870
4      PI1927 -70.816035 -33.574243
...       ...        ...        ...
11793   PC861 -70.506901 -33.332828
11794   PC596 -70.499667 -33.356539
11795   PC918 -70.499282 -33.343720
11796   PC919 -70.495669 -33.342486
11797   PC920 -70.496589 -33.340103

[11798 rows x 3 columns]

In [24]:
stops_df_1000 = exploded_df.sample(n = 1000).reset_index()
print(f"cant. normal: {len(stops_df)}\ncant. limpio: {len(stops_df_clean)}\ncant. a analizar: {len(stops_df_1000)}")
stops_df_1000

cant. normal: 11798
cant. limpio: 11798
cant. a analizar: 1000

     index    SIMT    Latitud   Longitud
0     4943   PH747 -70.654593 -33.509459
1     7755    PG91 -70.635905 -33.525982
2     6655   PB990 -70.734486 -33.349197
3      668  PG1927 -70.671440 -33.591969
4     7244  PB1403 -70.660306 -33.392289
..     ...     ...        ...        ...
995   1864   PF126 -70.574498 -33.611612
996  11154   PC321 -70.581223 -33.402328
997   1011  PF1119 -70.609909 -33.628984
998   4215    PH68 -70.699644 -33.526201
999   3315    PI28 -70.716359 -33.498839

[1000 rows x 4 columns]

In [3]:
# Creamos un dataframe que tenga todos los ID de paraderos de Santiago usando
# https://raw.githubusercontent.com/JoseDTPM/geojson-Transantiago/refs/heads/main/Paraderos-Santiago-Chile.geojsonl.json

import pandas as pd
import requests
import time
from datetime import datetime

def bus_routes(stop):
    all_routes_data = []
    total_stops = len(stop)
    i = 0
    for code in stop["SIMT"]:
        if i > 10:
            break
        i += 1
        print(f"Paradero actual: {code}")
        url = f"https://api.xor.cl/red/bus-stop/{code}"
        try:
            response = requests.get(url)
        except:
            break
        data = response.json()
        
        for service in data.get("services", []):
                for bus in service.get("buses", []):
                    current_datetime = datetime.now()
                    all_routes_data.append({
                        "bus_stop_code": code,
                        "route_id": service.get("id"),
                        "bus_id": bus.get("id"),
                        "meters_distance": bus.get("meters_distance"),
                        "min_arrival_time": bus.get("min_arrival_time"),
                        "max_arrival_time": bus.get("max_arrival_time"),
                        "date": current_datetime
            })
    bus_routes = pd.DataFrame(all_routes_data)
    final_df = pd.merge(
    bus_routes,
    stops_df,
    left_on="bus_stop_code",
    right_on="SIMT",
    how="left"
    )

    final_df = final_df.drop(columns=["SIMT"])
    return final_df


file = "data/Paraderos-Santiago-Chile.geojsonl.json"
df = pd.read_json(file, lines=True)
properties_df = pd.json_normalize(df["properties"])

# Seleccionamos la columna que corresponde al ID de los paraderos y sus coordenadas.
stops_df = properties_df[["SIMT", "X", "Y"]]
stops_df_clean = pd.DataFrame()
stops_df_clean["SIMT"] = stops_df["SIMT"].unique()
stops_df_1000 = stops_df.sample(n = 1000).reset_index()
timeanddate = datetime.now()
timeanddate = timeanddate.strftime("%d-%m-%Y-%H-%M")


final_bus_df = bus_routes(stops_df_1000)
final_bus_df

#final_bus_df.to_csv(f"buses_outputs/datos_{timeanddate}.csv", index=False)
#print("CSV creado.")

Paradero actual: PJ615
Paradero actual: PI509
Paradero actual: PE1474
Paradero actual: PB1103
Paradero actual: PB1941
Paradero actual: PC169
Paradero actual: PD76
Paradero actual: PA208
Paradero actual: PI1352
Paradero actual: PF782
Paradero actual: PE610

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,X,Y
0,PJ615,J02,VHXJ-22,2506,5,7,2025-10-21 11:15:43.767347,339908.155,6298792.190
1,PJ615,J02,VHXD-95,6762,18,26,2025-10-21 11:15:43.767362,339908.155,6298792.190
2,PJ615,J01,FLXG-47,793,4,6,2025-10-21 11:15:43.767367,339908.155,6298792.190
3,PJ615,J01,FLXS-81,2142,9,11,2025-10-21 11:15:43.767370,339908.155,6298792.190
4,PJ615,J08,FLXT-99,940,5,7,2025-10-21 11:15:43.767372,339908.155,6298792.190
5,PJ615,J08,RPYP-58,4026,13,19,2025-10-21 11:15:43.767374,339908.155,6298792.190
6,PJ615,J13,BJFC-86,3719,12,18,2025-10-21 11:15:43.767376,339908.155,6298792.190
7,PJ615,J13C,FLXS-87,3035,10,14,2025-10-21 11:15:43.767378,339908.155,6298792.190
8,PI509,419,PFYG-86,307,0,3,2025-10-21 11:16:00.868936,335062.847,6291589.843
9,PI509,419,PDYH-93,5127,14,20,2025-10-21 11:16:00.868949,335062.847,6291589.843
10,PI509,I07,VHTB-69,2738,8,10,2025-10-21 11:16:00.868952,335062.847,6291589.843
11,PE1474,233,SFPG-40,3411,8,10,2025-10-21 11:16:14.180131,349770.800,6289489.400
12,PE1474,233,SCRW-48,6934,18,26,2025-10-21 11:16:14.180144,349770.800,6289489.400
13,PB1103,B03,LJDL-48,105,0,3,2025-10-21 11:16:34.046230,337052.322,6303273.769
14,PB1103,B03,SKHG-57,3596,13,19,2025-10-21 11:16:34.046244,337052.322,6303273.769
15,PB1103,B09,SHCY-50,567,0,3,2025-10-21 11:16:34.046247,337052.322,6303273.769
16,PB1103,B09,SHCY-32,5912,17,25,2025-10-21 11:16:34.046249,337052.322,6303273.769
17,PB1103,B20,SKHG-69,860,0,4,2025-10-21 11:16:34.046251,337052.322,6303273.769
18,PB1103,B20,LXDJ-16,5625,25,60,2025-10-21 11:16:34.046252,337052.322,6303273.769
19,PB1941,B45,VHSY-11,1,0,3,2025-10-21 11:16:49.613177,339656.570,6307734.820
20,PB1941,B45,TWPC-56,2250,8,10,2025-10-21 11:16:49.613189,339656.570,6307734.820
21,PC169,407,TBFR-17,3856,13,17,2025-10-21 11:16:59.852337,356203.270,6302405.541
22,PC169,407,GCBD-50,5972,19,27,2025-10-21 11:16:59.852356,356203.270,6302405.541
23,PD76,D09,SVDB-99,1,0,3,2025-10-21 11:17:07.739248,351334.380,6297909.640
24,PD76,D09,SVDF-67,3983,16,22,2025-10-21 11:17:07.739270,351334.380,6297909.640
25,PD76,224,VFRD-35,7304,25,60,2025-10-21 11:17:07.739276,351334.380,6297909.640
26,PD76,224,VFPH-79,8816,25,60,2025-10-21 11:17:07.739280,351334.380,6297909.640
27,PA208,227,VFPJ-53,482,0,3,2025-10-21 11:17:13.675120,348011.150,6296146.550
28,PA208,227,VFPH-35,1659,5,7,2025-10-21 11:17:13.675133,348011.150,6296146.550
29,PI1352,405,PFVL-14,278,0,3,2025-10-21 11:17:20.125904,336790.811,6290317.593
30,PI1352,405,PDZS-78,3810,13,17,2025-10-21 11:17:20.125917,336790.811,6290317.593
31,PI1352,106,PFYS-50,1259,0,4,2025-10-21 11:17:20.125921,336790.811,6290317.593
32,PI1352,106,PFVJ-28,4469,14,20,2025-10-21 11:17:20.125923,336790.811,6290317.593
33,PI1352,401,PFYG-81,17,0,3,2025-10-21 11:17:20.125926,336790.811,6290317.593
34,PI1352,401,PFYH-10,1242,0,3,2025-10-21 11:17:20.125928,336790.811,6290317.593
35,PF782,F16,SPRW-68,1330,0,5,2025-10-21 11:17:23.506629,353396.244,6278789.135
36,PE610,E09,VKJX-31,1672,6,8,2025-10-21 11:17:27.134148,350044.195,6286349.536

In [4]:
def get_metro_data():
    url = "https://api.xor.cl/red/metro-network"
    all_stations_data = []

    response = requests.get(url)
    lines_data = response.json()

    lines_list = lines_data.get("lines", [])
    for line in lines_list:
        line_id = line.get("id")
        
        stations = line.get("stations", [])
        for station in stations:
            current_datetime = datetime.now()
            all_stations_data.append({
                "line_id": line_id,
                "station_id": station.get("id"),
                "name": station.get("name"),
                "status_code": station.get("status"),
                "status_description": station.get("description"),
                "date": current_datetime
            })

    return pd.DataFrame(all_stations_data)

timeanddate = datetime.now()
timeanddate = timeanddate.strftime("%d-%m-%Y-%H-%M")
    
metro_df = get_metro_data()
metro_df
#metro_df.to_csv(f"metro_outputs/metro_{timeanddate}.csv", index=False)

,line_id,station_id,name,status_code,status_description,date
0,L1,san-pablo,San Pablo,0,Estación Operativa,2025-10-21 11:17:42.453460
1,L1,neptuno,Neptuno,0,Estación Operativa,2025-10-21 11:17:42.453478
2,L1,pajaritos,Pajaritos,0,Estación Operativa,2025-10-21 11:17:42.453484
3,L1,las-rejas,Las Rejas,0,Estación Operativa,2025-10-21 11:17:42.453487
4,L1,ecuador,Ecuador,0,Estación Operativa,2025-10-21 11:17:42.453490
...,...,...,...,...,...,...
138,L6,nuble,Ñuble,0,Estación Operativa,2025-10-21 11:17:42.454461
139,L6,estadio-nacional,Estadio Nacional,0,Estación Operativa,2025-10-21 11:17:42.454462
140,L6,nunoa,Ñuñoa,0,Estación Operativa,2025-10-21 11:17:42.454463
141,L6,ines-de-suarez,Inés de Suárez,0,Estación Operativa,2025-10-21 11:17:42.454464
142,L6,los-leones,Los Leones,0,Estación Operativa,2025-10-21 11:17:42.454466